// ignore_for_file: non_constant_identifier_names, camel_case_types
// ignore_for_file: library_private_types_in_public_api
//
// Hand-authored FFI bindings for the focused subset of `src/toggl_api.h` the app
// uses directly. The full ~205-function surface is generated by `ffigen`
// (config `app/ffigen.yaml`) into `toggl_api_generated.dart`. Implements FP-20.
//
// ABI notes (see ADR-0001):
//  * `char_t` == `char` (UTF-8) on every target — the core MUST be built without
//    `UNICODE`, so even Windows uses the `char` ABI.
//  * `bool_t` == `int` (NOT C99 `_Bool`); bind it as `Int`/`int`.
//  * Every `toggl_on_*` registrar takes `(void* ctx, <fnptr> cb)`. A function
//    pointer is ABI-identical regardless of the callee signature, so ALL
//    registrars share one generic [onRegister] lookup; only the NativeCallable
//    we build for each callback needs the precise signature below.

import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';

/// `TogglTimeEntryView` from `src/toggl_api.h` (lines 47-97).
/// Field order and types MUST match the C struct exactly.
final class TogglTimeEntryView extends ffi.Struct {
  @ffi.Uint64()
  external int ID;
  @ffi.Int64()
  external int DurationInSeconds;
  external ffi.Pointer<Utf8> Description;
  external ffi.Pointer<Utf8> ProjectAndTaskLabel;
  external ffi.Pointer<Utf8> TaskLabel;
  external ffi.Pointer<Utf8> ProjectLabel;
  external ffi.Pointer<Utf8> ClientLabel;
  @ffi.Uint64()
  external int WID;
  @ffi.Uint64()
  external int PID;
  @ffi.Uint64()
  external int TID;
  external ffi.Pointer<Utf8> Duration;
  external ffi.Pointer<Utf8> Color;
  external ffi.Pointer<Utf8> GUID;
  @ffi.Int()
  external int Billable; // bool_t
  @ffi.Uint64()
  external int ActivityID; // Redmine activity id
  external ffi.Pointer<Utf8> Tags;
  @ffi.Uint64()
  external int Started;
  @ffi.Uint64()
  external int Ended;
  external ffi.Pointer<Utf8> StartTimeString;
  external ffi.Pointer<Utf8> EndTimeString;
  @ffi.Uint64()
  external int UpdatedAt;
  @ffi.Int()
  external int DurOnly;
  external ffi.Pointer<Utf8> DateHeader;
  external ffi.Pointer<Utf8> DateDuration;
  @ffi.Int()
  external int IsHeader;
  @ffi.Int()
  external int CanAddProjects;
  @ffi.Int()
  external int CanSeeBillable;
  @ffi.Uint64()
  external int DefaultWID;
  external ffi.Pointer<Utf8> WorkspaceName;
  external ffi.Pointer<Utf8> Error;
  @ffi.Int()
  external int Locked;
  @ffi.Int()
  external int Unsynced;
  @ffi.Int()
  external int Group;
  @ffi.Int()
  external int GroupOpen;
  external ffi.Pointer<Utf8> GroupName;
  external ffi.Pointer<Utf8> GroupDuration;
  @ffi.Uint64()
  external int GroupItemCount;
  @ffi.Uint64()
  external int RoundedStart;
  @ffi.Uint64()
  external int RoundedEnd;

  /// `void *Next` — next node in the linked list (null-terminated).
  external ffi.Pointer<TogglTimeEntryView> Next;
}

// --- Callback native signatures (the `TogglDisplay*` typedefs) ---

/// `TogglDisplayApp(bool_t open)`
typedef DisplayAppNative = ffi.Void Function(ffi.Int open);

/// `TogglDisplayTimeEntryList(bool_t open, TogglTimeEntryView* first, bool_t showLoadMore)`
typedef DisplayTimeEntryListNative = ffi.Void Function(
    ffi.Int open, ffi.Pointer<TogglTimeEntryView> first, ffi.Int showLoadMore);

/// `TogglDisplayTimerState(TogglTimeEntryView* te)` — `te` is null when stopped.
typedef DisplayTimerStateNative = ffi.Void Function(
    ffi.Pointer<TogglTimeEntryView> te);

/// `TogglDisplayLogin(bool_t open, uint64_t user_id)`
typedef DisplayLoginNative = ffi.Void Function(ffi.Int open, ffi.Uint64 userId);

/// `TogglDisplayError(const char_t* errmsg, bool_t user_error)`
typedef DisplayErrorNative = ffi.Void Function(
    ffi.Pointer<Utf8> errmsg, ffi.Int userError);

/// `TogglDisplayOnlineState(int64_t state)`
typedef DisplayOnlineStateNative = ffi.Void Function(ffi.Int64 state);

/// `TogglDisplayURL(const char_t* url)`
typedef DisplayUrlNative = ffi.Void Function(ffi.Pointer<Utf8> url);

/// Two-string callbacks: reminder / pomodoro / pomodoro-break.
typedef DisplayString2Native = ffi.Void Function(
    ffi.Pointer<Utf8> a, ffi.Pointer<Utf8> b);

/// `TogglDisplaySettings(bool_t open, TogglSettingsView* settings)`
typedef DisplaySettingsNative = ffi.Void Function(
    ffi.Int open, ffi.Pointer<ffi.Void> settings);

/// `TogglDisplayTimeEntryEditor(bool_t open, TogglTimeEntryView* te, const char_t* field)`
typedef DisplayEditorNative = ffi.Void Function(ffi.Int open,
    ffi.Pointer<TogglTimeEntryView> te, ffi.Pointer<Utf8> focusedField);

/// `TogglDisplayIdleNotification(guid, since, duration, started, desc, project, task, projectColor)`
typedef DisplayIdleNative = ffi.Void Function(
    ffi.Pointer<Utf8> guid,
    ffi.Pointer<Utf8> since,
    ffi.Pointer<Utf8> duration,
    ffi.Int64 started,
    ffi.Pointer<Utf8> description,
    ffi.Pointer<Utf8> project,
    ffi.Pointer<Utf8> task,
    ffi.Pointer<Utf8> projectColor);

/// Any callback whose sole argument is a pointer-to-view we don't model yet
/// (autocomplete, tags, workspace/client select). ABI: one pointer arg.
typedef DisplayViewPtrNative = ffi.Void Function(ffi.Pointer<ffi.Void> first);

// --- Exported plain functions ---

typedef _CtxInitNative = ffi.Pointer<ffi.Void> Function(
    ffi.Pointer<Utf8>, ffi.Pointer<Utf8>);
typedef _CtxInitDart = ffi.Pointer<ffi.Void> Function(
    ffi.Pointer<Utf8>, ffi.Pointer<Utf8>);

typedef _CtxVoidNative = ffi.Void Function(ffi.Pointer<ffi.Void>);
typedef _CtxVoidDart = void Function(ffi.Pointer<ffi.Void>);

typedef _CtxStrIntNative = ffi.Int Function(
    ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>);
typedef _CtxStrIntDart = int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>);

typedef _CtxStrVoidNative = ffi.Void Function(
    ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>);
typedef _CtxStrVoidDart = void Function(
    ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>);

typedef _StrVoidNative = ffi.Void Function(ffi.Pointer<Utf8>);
typedef _StrVoidDart = void Function(ffi.Pointer<Utf8>);

typedef _CtxIntNative = ffi.Int Function(ffi.Pointer<ffi.Void>);
typedef _CtxIntDart = int Function(ffi.Pointer<ffi.Void>);

typedef _LoginNative = ffi.Int Function(
    ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>, ffi.Pointer<Utf8>);
typedef _LoginDart = int Function(
    ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>, ffi.Pointer<Utf8>);

typedef _StopNative = ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Int);
typedef _StopDart = int Function(ffi.Pointer<ffi.Void>, int);

// Editor setters of shape `bool_t f(ctx, guid, value)`.
typedef _GuidValNative = ffi.Int Function(
    ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>, ffi.Pointer<Utf8>);
typedef _GuidValDart = int Function(
    ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>, ffi.Pointer<Utf8>);

// `bool_t toggl_set_time_entry_billable(ctx, guid, bool_t)`.
typedef _GuidBoolNative = ffi.Int Function(
    ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>, ffi.Int);
typedef _GuidBoolDart = int Function(
    ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>, int);

// `void toggl_edit(ctx, guid, bool_t edit_running, const char* focused_field)`.
typedef _EditNative = ffi.Void Function(ffi.Pointer<ffi.Void>,
    ffi.Pointer<Utf8>, ffi.Int, ffi.Pointer<Utf8>);
typedef _EditDart = void Function(
    ffi.Pointer<ffi.Void>, ffi.Pointer<Utf8>, int, ffi.Pointer<Utf8>);

// `char* toggl_start(ctx, desc, duration, task_id, project_id, project_guid, tags, prevent_on_app, started, ended)`.
typedef _StartNative = ffi.Pointer<Utf8> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<Utf8>,
    ffi.Pointer<Utf8>,
    ffi.Uint64,
    ffi.Uint64,
    ffi.Pointer<Utf8>,
    ffi.Pointer<Utf8>,
    ffi.Int,
    ffi.Uint64,
    ffi.Uint64);
typedef _StartDart = ffi.Pointer<Utf8> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<Utf8>,
    ffi.Pointer<Utf8>,
    int,
    int,
    ffi.Pointer<Utf8>,
    ffi.Pointer<Utf8>,
    int,
    int,
    int);

/// Generic `toggl_on_*` registrar: `void f(void* ctx, <fnptr> cb)`.
typedef _OnRegisterNative = ffi.Void Function(
    ffi.Pointer<ffi.Void> ctx, ffi.Pointer<ffi.Void> cb);
typedef OnRegister = void Function(
    ffi.Pointer<ffi.Void> ctx, ffi.Pointer<ffi.Void> cb);

/// Typed wrapper over `libTogglDesktopLibrary` for the subset the app calls.
class TogglBindings {
  TogglBindings(this._lib)
      : contextInit = _lib.lookupFunction<_CtxInitNative, _CtxInitDart>(
            'toggl_context_init'),
        contextClear = _lib.lookupFunction<_CtxVoidNative, _CtxVoidDart>(
            'toggl_context_clear'),
        setDbPath = _lib.lookupFunction<_CtxStrIntNative, _CtxStrIntDart>(
            'toggl_set_db_path'),
        setLogPath = _lib.lookupFunction<_StrVoidNative, _StrVoidDart>(
            'toggl_set_log_path'),
        setCacertPath =
            _lib.lookupFunction<_CtxStrVoidNative, _CtxStrVoidDart>(
                'toggl_set_cacert_path'),
        setBaseUrl = _lib.lookupFunction<_CtxStrVoidNative, _CtxStrVoidDart>(
            'toggl_set_base_url'),
        uiStart =
            _lib.lookupFunction<_CtxIntNative, _CtxIntDart>('toggl_ui_start'),
        login = _lib.lookupFunction<_LoginNative, _LoginDart>('toggl_login'),
        logout =
            _lib.lookupFunction<_CtxIntNative, _CtxIntDart>('toggl_logout'),
        continueEntry = _lib.lookupFunction<_CtxStrIntNative, _CtxStrIntDart>(
            'toggl_continue'),
        stop = _lib.lookupFunction<_StopNative, _StopDart>('toggl_stop'),
        deleteTimeEntry =
            _lib.lookupFunction<_CtxStrIntNative, _CtxStrIntDart>(
                'toggl_delete_time_entry'),
        setDescription = _lib.lookupFunction<_GuidValNative, _GuidValDart>(
            'toggl_set_time_entry_description'),
        setDuration = _lib.lookupFunction<_GuidValNative, _GuidValDart>(
            'toggl_set_time_entry_duration'),
        setStart = _lib.lookupFunction<_GuidValNative, _GuidValDart>(
            'toggl_set_time_entry_start'),
        setEnd = _lib.lookupFunction<_GuidValNative, _GuidValDart>(
            'toggl_set_time_entry_end'),
        setTags = _lib.lookupFunction<_GuidValNative, _GuidValDart>(
            'toggl_set_time_entry_tags'),
        setBillable = _lib.lookupFunction<_GuidBoolNative, _GuidBoolDart>(
            'toggl_set_time_entry_billable'),
        edit = _lib.lookupFunction<_EditNative, _EditDart>('toggl_edit'),
        start = _lib.lookupFunction<_StartNative, _StartDart>('toggl_start');

  final ffi.DynamicLibrary _lib;

  final _CtxInitDart contextInit;
  final _CtxVoidDart contextClear;
  final _CtxStrIntDart setDbPath;
  final _StrVoidDart setLogPath;
  final _CtxStrVoidDart setCacertPath;
  final _CtxStrVoidDart setBaseUrl;
  final _CtxIntDart uiStart;
  final _LoginDart login;
  final _CtxIntDart logout;
  final _CtxStrIntDart continueEntry;
  final _StopDart stop;
  final _CtxStrIntDart deleteTimeEntry;
  final _GuidValDart setDescription;
  final _GuidValDart setDuration;
  final _GuidValDart setStart;
  final _GuidValDart setEnd;
  final _GuidValDart setTags;
  final _GuidBoolDart setBillable;
  final _EditDart edit;
  final _StartDart start;

  /// Looks up a `toggl_on_*` registrar by symbol name (generic fn-ptr ABI).
  OnRegister onRegister(String symbol) =>
      _lib.lookupFunction<_OnRegisterNative, OnRegister>(symbol);
}
